---
repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v5.0.0
      hooks:
          - id: trailing-whitespace
            name: (Common) Remove trailing whitespaces
          - id: mixed-line-ending
            name: (Common) Fix mixed line ending
            args: [--fix=lf]
          - id: end-of-file-fixer
            name: (Common) Remove extra EOF newlines
          - id: check-merge-conflict
            name: (Common) Check for merge conflicts
          - id: requirements-txt-fixer
            name: (Common) Sort "requirements.txt"
          - id: fix-encoding-pragma
            name: (Python) Remove encoding pragmas
            args: [--remove]
          - id: debug-statements
            name: (Python) Check for debugger imports
          - id: check-json
            name: (JSON) Check syntax
          - id: check-yaml
            name: (YAML) Check syntax
          - id: check-toml
            name: (TOML) Check syntax
    - repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt
      rev: 0.2.3 # or other specific tag
      hooks:
          - id: yamlfmt

    - repo: https://github.com/executablebooks/mdformat
      rev: 0.7.17
      hooks:
          - id: mdformat
            name: (Markdown) Format docs with mdformat
    - repo: https://github.com/asottile/pyupgrade
      rev: v3.17.0
      hooks:
          - id: pyupgrade
            name: (Python) Update syntax for newer versions
            args: [--py37-plus]
    - repo: https://github.com/pycqa/isort
      rev: 5.13.2
      hooks:
          - id: isort
            name: (Python) Sort imports with isort
    - repo: https://github.com/psf/black
      rev: 24.10.0
      hooks:
          - id: black
            name: (Python) Format code with black
    - repo: https://github.com/pre-commit/mirrors-clang-format
      rev: v19.1.1
      hooks:
          - id: clang-format
            name: (C/C++/CUDA) Format code with clang-format
            args: [-style=google, -i]
            types_or: [c, c++, cuda]
